# Generated by Django 2.2 on 2020-03-02 07:42

from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='document',
            field=models.FileField(upload_to=notification.models.upload_image_path),
        ),
    ]
