# Generated by Django 2.2 on 2020-03-02 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200302_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
