# Generated by Django 2.2 on 2020-03-02 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200302_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
